use serde::{Deserialize, Serialize};

/// POST payload for inserting new debt series, pricing, and service
#[derive(Serialize, Deserialize)]
pub struct DebtSeriesPostJson {
    pub debt_series: Vec<DebtSeriesInsert>,
    pub debt_pricing: Vec<DebtPricingInsert>,
    pub debt_service: Vec<DebtServiceInsert>,
}

/// Insert version of DebtSeries (no ID)
#[derive(Serialize, Deserialize)]
pub struct DebtSeriesInsert {
    pub series_name: String,
    pub is_tax_exempt: Option<bool>,
    pub par_amount: f64,
    pub premium: Option<f64>,
    pub cost_of_issuance: Option<f64>,
    pub created_at: Option<String>,
}

/// Insert version of DebtPricing (ID generated by DB)
#[derive(Serialize, Deserialize)]
pub struct DebtPricingInsert {
    pub series_id: i64,        // parent series must exist in DB after insert
    pub maturity_date: String, // YYYY-MM-DD
    pub amount: f64,
    pub coupon_rate: f64,
    pub yield_rate: f64,
    pub price: f64,
    pub premium_discount: Option<f64>,
    pub created_at: Option<String>,
}

/// Insert version of DebtService (ID generated by DB)
#[derive(Serialize, Deserialize)]
pub struct DebtServiceInsert {
    pub series_id: i64,       // parent series must exist in DB after insert
    pub payment_date: String, // YYYY-MM-DD
    pub principal: Option<f64>,
    pub interest: Option<f64>,
    pub created_at: Option<String>,
}
